from enum import Enum


class TaskState(Enum):
    CREATED = "CREATED"
    WAITING_REVIEW = "WAITING_REVIEW"
    RUNNING = "RUNNING"
    CANCELED = "CANCELED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class EventType(Enum):
    ACCEPTED = "accepted"
    PROGRESS = "progress"
    REASONING = "reasoning"
    CHUNK = "chunk"
    A2UI = "a2ui"
    DONE = "done"
    ERROR = "error"
    HEARTBEAT = "heartbeat"


class ExecutionMode(Enum):
    SEND = "SEND"
    STREAM = "STREAM"


class Decision(Enum):
    APPROVE = "APPROVE"
    CANCEL = "CANCEL"


class ReasonCode(Enum):
    SUCCESS = "SUCCESS"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    SESSION_OWNERSHIP_MISMATCH = "SESSION_OWNERSHIP_MISMATCH"
    TASK_STATE_INVALID = "TASK_STATE_INVALID"
    SNAPSHOT_NOT_FOUND = "SNAPSHOT_NOT_FOUND"
    SNAPSHOT_EXPIRED = "SNAPSHOT_EXPIRED"
    RESUME_TOKEN_MISMATCH = "RESUME_TOKEN_MISMATCH"
    STATE_VERSION_MISMATCH = "STATE_VERSION_MISMATCH"
    REQUEST_HASH_MISMATCH = "REQUEST_HASH_MISMATCH"
    FROZEN_PLAN_HASH_MISMATCH = "FROZEN_PLAN_HASH_MISMATCH"
    PLAN_DRIFT_BLOCKED = "PLAN_DRIFT_BLOCKED"
    DUPLICATE_DECISION = "DUPLICATE_DECISION"
    ALREADY_TERMINAL = "ALREADY_TERMINAL"
    EXECUTION_FAILURE = "EXECUTION_FAILURE"
